[package]
name = "ray_tracer"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "ray_tracer"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
byteorder = "1.3.4"
rustler = "0.22.0-rc.0"
